config/routes.rb
Rails.application.routes.draw do
  resources :documents

  # CODAP API
  get 'document/all' => 'documents#all'
  get 'document/open' => 'documents#open'
  get 'document/launch' => 'documents#launch', :as => :launch
  get 'document/report' => 'documents#report', :as => :report
  post 'document/save' => 'documents#save'
  post 'document/patch' => 'documents#patch'
  get 'document/rename' => 'documents#rename'
  get 'document/delete' => 'documents#delete'
  get 'user/info' => 'users#info'
  get 'user/authenticate' => 'users#authenticate'

  get 'v2/documents/:id' => 'documents_v2#open', :as => :v2_document_open
  put 'v2/documents/:id' => 'documents_v2#save', :as => :v2_document_save
  patch 'v2/documents/:id' => 'documents_v2#patch', :as => :v2_document_patch
  post 'v2/documents' => 'documents_v2#create', :as => :v2_document_create
  get 'v2/documents/:id/launch' => 'documents_v2#launch', :as => :v2_document_launch
  get 'v2/documents/:id/autolaunch' => 'documents_v2#autolaunch', :as => :v2_document_autolaunch
  post 'v2/documents/create_keys' => 'documents_v2#create_keys', :as => :v2_document_create_keys

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks"}
  resources :users

  #examples
  get "/examples/:example" => "examples#show"
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :owner, inverse_of: :documents, class_name: 'User'
  has_one :contents, class_name: 'DocumentContent', dependent: :destroy, autosave: true

  has_many :children, class_name: 'Document', foreign_key: 'parent_id', dependent: :destroy
  belongs_to :parent, class_name: 'Document' #, dependent: :destroy -- handled in after_destroy :destroy_parent

  delegate :content, :content=, :original_content, :original_content=, to: :contents

  scope :shared, -> { where(shared: true) }

  validates :title, uniqueness: {scope: [:owner, :run_key]}, if: :has_owner?
  validate :validate_form_content

  after_save :sync_attributes
  #before_destroy :store_parent
  #after_destroy :destroy_parent # workaround for https://github.com/rails/rails/issues/13609

  def form_content=(new_content)
    if new_content.is_json?
      self.content = new_content.parsed_json
      @form_content = nil
    else
      @form_content = new_content
    end
  end

  def form_content
    @form_content || (content && content.to_json) || ""
  end

  def contents_with_check
    self.contents_without_check || (self.contents = DocumentContent.new)
  end
  alias_method_chain :contents, :check

  def create_access_keys
    # generate two unique new access keys - we can't use a unique index constraint because the keys will be null for older documents
    # giving the length of the random strings this will probably never loop
    read_access_key = nil
    read_write_access_key = nil
    loop do
      read_access_key = SecureRandom.hex(20)
      read_write_access_key = SecureRandom.hex(40)
      break if !Document.find_by(read_access_key: read_access_key) && !Document.find_by(read_write_access_key: read_write_access_key)
    end
    self.read_access_key = read_access_key if self.read_access_key.nil?
    self.read_write_access_key = read_write_access_key if self.read_write_access_key.nil?
  end

  protected

  def validate_form_content
    if form_content && !form_content.is_json?
      errors.add(:form_content, "must be valid json")
    end
  end

  def sync_attributes
    is_main_doc = contents.is_codap_main_document
    is_main_doc_dirty = is_codap_main_document != is_main_doc

    atts_to_update = {}
    atts_to_update[:is_codap_main_document] = is_main_doc if is_main_doc_dirty
    update_columns(atts_to_update) if atts_to_update.size > 0

    return true
  end

  def store_parent
    @saved_parent = parent
    self.parent = nil
  end

  def destroy_parent
    return unless @saved_parent
    @saved_parent.destroy unless @saved_parent.destroyed?
  end

  def has_owner?
    self.owner != nil
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :auto_authenticate, :only => [:launch]
  before_filter :authenticate_user!, :except => [:index, :show, :all, :open, :save, :patch, :delete, :launch, :rename, :report]
  before_filter :run_key_or_authenticate, :only => [:index, :show]
  before_filter :load_index_documents, :only => [:index, :all]
  load_and_authorize_resource
  skip_load_and_authorize_resource :only => [:all, :save, :patch, :open, :delete, :launch, :rename, :report]
  skip_before_filter :verify_authenticity_token, :only => [:save, :patch]

  before_filter :check_session_expiration, :only => [:all, :save, :patch, :open, :delete, :rename]

  after_filter :log_access, :only => [:show, :edit, :create, :update, :destroy, :open, :save, :patch, :rename, :delete]

  include DocumentsHelper

  cattr_accessor :run_key_generator
  self.run_key_generator = lambda { return SecureRandom.uuid }

  # GET /documents
  # GET /documents.json
  def index
    @documents = @documents.includes(:children).paginate(page: index_params[:page], :per_page => 20) if @documents.respond_to?('paginate')
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @document.owner = current_user

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  # CODAP API
  def all
    authorize! :all, Document rescue (render_not_authorized && return)
    render json: @documents.map {|d| {name: d.title, id: d.id, _permissions: (d.shared ? 1 : 0) } }
  end

  def open
    @document = find_doc_via_params
    new_doc = nil
    render_not_found && return unless @document
    content = @document.content
    if codap_api_params[:original]
      begin
        authorize! :open_original, @document
        content = @document.original_content || @document.content
      rescue
      end
    else
      authorize! :open, @document rescue (render_not_authorized && return)
    end
    if @document.owner != current_user
      content["_permissions"] = 0 if content && content.is_a?(Hash) && content.has_key?("_permissions")
      if can?(:save, :document)
        # check if a document exists with the same name for the current_user
        new_doc = Document.find_or_initialize_by(owner: current_user, title: @document.title, run_key: codap_api_params[:runKey] )
        new_doc_existed = !new_doc.new_record?
      end
    end
    response.headers['Document-Id'] = "#{@document.id}"
    response.headers['X-Codap-Opened-From-Shared-Document'] = "true" if new_doc
    response.headers['X-Codap-Will-Overwrite'] = "true" if new_doc && new_doc_existed
    render json: content
  end

  def save
    content = request.raw_post

    warn_overwrite = false
    if codap_api_params[:recordid].present?
      @document = Document.find(codap_api_params[:recordid].to_i)
      @access_params = {recordid: codap_api_params[:recordid]}
    else
      @document = Document.find_or_initialize_by(owner: current_user, title: codap_api_params[:recordname], run_key: codap_api_params[:runKey])
      @access_params = {owner: current_user ? current_user.id : nil, title: codap_api_params[:recordname], run_key: codap_api_params[:runKey]}
      warn_overwrite = !@document.new_record? && !codap_api_params[:runKey]
    end
    begin
      authorize! :save, @document
    rescue
      if @document.owner == current_user
        render_not_authorized
        return
      else
        new_doc = Document.find_or_initialize_by(owner: current_user, title: codap_api_params[:recordname] || @document.title, run_key: codap_api_params[:runKey] )
        if new_doc.new_record? || codap_api_params[:runKey]
          @document = new_doc
        else
          warn_overwrite = true
        end
      end
    end

    if warn_overwrite
      render_duplicate_error
      return
    end

    @document.form_content = content
    @document.original_content = @document.content if @document.new_record?
    @document.shared = @document.content.is_a?(Hash) && @document.content.has_key?('_permissions') && @document.content['_permissions'].to_i == 1
    @document.parent_id = codap_api_params[:parentDocumentId].to_i if codap_api_params[:parentDocumentId].present?

    if @document.save
      render json: {status: "Created", valid: true, id: @document.id }, status: :created
    else
      render json: {status: "Error", errors: @document.errors.full_messages, valid: false, message: 'error.writeFailed' }, status: 400
    end
  end

  def patch
    if codap_api_params[:recordid].present?
      @document = Document.find(codap_api_params[:recordid].to_i)
      @access_params = {recordid: codap_api_params[:recordid]}
    else
      render_not_found
      return
    end
    authorize! :save, @document rescue (render_not_authorized && return)

    begin
      patchset = JSON.parse(request.raw_post)
      raise "Empty patchset" unless patchset && patchset.is_a?(Array)
    rescue => e
      render json: {status: "Error", errors: ["Invalid patch JSON (parsing)", e.to_s, patchset], valid: false, message: 'error.writeFailed' }, status: 400
      return
    end

    begin
      # Use JSON Patch to bring the content up-to-date
      res = JSON::Patch.new(@document.content, patchset).call

      shared = res.is_a?(Hash) && res.has_key?('_permissions') && res['_permissions'].to_i == 1

      doc_updates = {updated_at: Time.current, shared: shared}
      doc_updates[:parent_id] = codap_api_params[:parentDocumentId].to_i if codap_api_params[:parentDocumentId].present?

      # Just using '@document.content = res; @document.save' didn't seem to actually persist things, so we'll be more forceful.
      if @document.update_columns(doc_updates) && @document.contents.update_columns({content: res, updated_at: Time.current})
        render json: {status: "Patched", valid: true, id: @document.id }, status: 200
      else
        render json: {status: "Error", errors: @document.errors.full_messages + @document.contents.errors.full_messages, valid: false, message: 'error.writeFailed' }, status: 400
      end
    rescue => e
      render json: {status: "Error", errors: ["Invalid patch JSON (executing)", e.to_s], valid: false, message: 'error.writeFailed' }, status: 400
    end

  end

  def rename
    @document = find_doc_via_params
    (render_not_found && return) unless @document
    authorize! :save, @document rescue (render_not_authorized && return)
    owner_id = current_user.nil? ? nil : current_user.id
    newDoc = Document.find_by(owner_id: owner_id, title: codap_api_params[:newRecordname], run_key: codap_api_params[:runKey])

    if newDoc
      # render error!
      render_duplicate_error
    else
      c = @document.content
      oc = @document.original_content
      c["name"] = codap_api_params[:newRecordname] if c.has_key?("name")
      oc["name"] = codap_api_params[:newRecordname] if oc && oc.has_key?("name")
      @document.update_columns(title: codap_api_params[:newRecordname], updated_at: Time.now)
      @document.contents.update_columns(content: c, updated_at: Time.now)
      render json: {success: true }
    end
  end

  def delete
    opts = delete_params
    opts[:owner] = current_user.username if current_user
    @document = find_doc_via_params(opts)
    (render_not_found && return) unless @document
    authorize! :destroy, @document rescue (render_not_authorized && return)
    @document.destroy
    render json: {success: true}
  end

  def launch
    @codap_server = launch_params[:server]
    @runKey = launch_params[:runKey] || self.run_key_generator.call

    if launch_params[:recordid] || (launch_params[:owner] && (launch_params[:recordname] || launch_params[:doc]))
      original_doc = find_doc_via_params(launch_params)
      @master_document_url = codap_link(@codap_server, original_doc, false, true) if original_doc
    elsif launch_params[:moreGames]
      moreGames = launch_params[:moreGames]
      moreGames = moreGames.to_json if moreGames.is_a?(Hash) || moreGames.is_a?(Array)
      @master_document_url = codap_link(@codap_server, moreGames, false, true)
    end

    @buttonText = launch_params[:buttonText] || 'Launch'

    @supplemental_documents = Document.where(owner_id: (current_user ? current_user.id : nil), run_key: @runKey).select{|d| d.is_codap_main_document? }

    @learner_url = Addressable::URI.parse(request.original_url)
    new_query = @learner_url.query_values || {}
    new_query["runKey"] = @runKey
    new_query.delete("auth_provider")
    new_query.delete("require_email")
    new_query.delete("require_anonymous")
    new_query.delete("auto_auth_in_progress")
    @learner_url.query_values = new_query

    @report_url = @learner_url.dup
    @report_url.path = report_path

    new_query = @report_url.query_values || {}

app/helpers/documents_helper.rb
module DocumentsHelper
  def codap_link(codap_server, document, runAsGuest=false, fromLaunchPage=false)
    data = {
      "documentServer" => root_url(protocol: 'https')
    }
    rkey = (@runKey || document.run_key)
    data["runKey"] = rkey if rkey
    if document.is_a?(Document)
      data["recordid"] = document.id
    else
      data["moreGames"] = document
    end
    data["runAsGuest"] = 'true' if runAsGuest
    data["launchFromLara"] = 'true' if fromLaunchPage

    url = Addressable::URI.parse(codap_server || ENV['CODAP_DEFAULT_URL'] || 'https://codap.concord.org/releases/latest/')
    new_query = url.query_values || {}
    new_query.merge!(data)
    url.query_values = new_query
    return url.to_s
  end
end

app/views/documents/_form.html.haml
= simple_form_for @document do |f|
  = f.error_notification

  = f.input :title, as: :string
  = f.input :form_content, as: :text, label: "Content", input_html: { rows: 10 }
  = f.input :shared
  = f.button :submit

app/views/documents/_reveal_modal.html.haml
- current_codap_server = (session[:codap_server_url] || ENV['CODAP_DEFAULT_URL'] || 'https://codap.concord.org/releases/latest/')
- link = launch_url(server: current_codap_server, recordid: document.id, :protocol => 'https')
.reveal-modal{id: "linkModal#{document.id}", "data-reveal" => true}
  %h3= "Launch Link"
  %label
    Use this link when creating an activity in LARA:
    %textarea{id: "launchLink#{document.id}", readonly: true}= link
  %h4= "Advanced Options"
  %label
    CODAP Server URL:
    %input{id: "codapServer#{document.id}", type: 'text', placeholder: 'Enter CODAP server url here...', value: current_codap_server}
  %label
    Launch Button Text:
    %input{id: "buttonText#{document.id}", type: 'text', placeholder: 'Enter launch button text here...', value: 'Launch'}
  %a.close-reveal-modal= "&#215;".html_safe

:javascript
  $('#codapServer#{document.id}').on('input propertychange paste', function() {
    var currUrl = $("#launchLink#{document.id}").val();
    $("#launchLink#{document.id}").val($.param.querystring(currUrl, {server: $(this).val()} ));
  });

  $('#buttonText#{document.id}').on('input propertychange paste', function() {
    var currUrl = $("#launchLink#{document.id}").val();
    $("#launchLink#{document.id}").val($.param.querystring(currUrl, {buttonText: $(this).val()} ));
  });

  $('#launchLink#{document.id}').mouseup(function(e) {
    e.preventDefault();
    $("#launchLink#{document.id}").select();
  });

app/views/documents/edit.html.haml
%ul.breadcrumbs
  %li= link_to 'Home', root_path
  %li= link_to 'Documents', documents_path
  %li= link_to @document.title, document_path(@document)
  %li.current
    %a{href: '#'} Edit

%h1 Editing document

= render 'form'

app/views/documents/index.html.haml
%h1 Your documents

- docs_with_dialogs = []

= will_paginate(@documents, renderer: FoundationPagination::Rails)

%table.document_list
  %thead
    %tr
      %th{width: 500} Title
      %th{width:  68} Shared
      %th{width:  63}
      %th{width:  44}
      %th{width:  61}
      %th{width:  67}
      %th{width:  58}

  %tbody
    - @documents.each do |document|
      %tr.wrapper.collapsed
        %td.title= (document.title || "") + (document.run_key ? " [#{document.run_key}]" : "")
        %td.centered
          - if document.shared
            %span.green-check &#x2714;

        %td= " "
        %td= " "
        - if can? :destroy, document
          %td= link_to 'Delete', document, :method => :delete, :data => { :confirm => 'Are you sure?' }
        - else
          %td= " "
        - if can?(:open, document) && document.is_codap_main_document?
          %td= link_to 'Launch', codap_link(nil, document), target: "_blank"
        - else
          %td= " "
        - if can?(:update, document) && document.shared && document.is_codap_main_document?
          - docs_with_dialogs << document
          %td
            %a.link_button{href: '#', "data-reveal-id" => "linkModal#{document.id}"}= 'Link...'
        - else
          %td= " "
      %tr.doc_part
        %td.title= (document.title || "") + (document.run_key ? " [#{document.run_key}]" : "")
        %td.centered= " "
        - if can? :read, document
          %td= link_to 'Details', document
        - else
          %td= " "
        - if can? :update, document
          %td= link_to 'Edit', edit_document_path(document)
        - else
          %td= " "
        %td= " "
        %td= " "
        %td= " "
      - document.children.each do |child|
        %tr.doc_part
          %td.title= (child.title || "") + (child.run_key ? " [#{document.run_key}]" : "")
          %td.centered= " "
          - if can? :read, child
            %td= link_to 'Details', child
          - else
            %td= " "
          - if can? :update, child
            %td= link_to 'Edit', edit_document_path(child)
          - else
            %td= " "
          %td= " "
          %td= " "
          %td= " "

= will_paginate(@documents, renderer: FoundationPagination::Rails)

:javascript
  $(document).ready(function() {
    $('.doc_part').hide();
    function getChildren($row) {
      var children = [];
      while($row.next().hasClass('doc_part')) {
        children.push($row.next());
        $row = $row.next();
      }
      return children;
    }

    $('.wrapper').on('click', function() {
      var children = getChildren($(this));
      $.each(children, function() {
        $(this).toggle();
      })
      if ($(this).hasClass('expanded')) {
        $(this).removeClass('expanded').addClass('collapsed');
      } else {
        $(this).removeClass('collapsed').addClass('expanded');
      }
    });
  })

%br

- if can? :create, Document
  = link_to 'Create Document', new_document_path, class: :button

- docs_with_dialogs.each do |document|
  = render partial: 'reveal_modal', locals: {document: document}

app/views/documents/launch.html.haml
.row.login-error{style: "display: none;"}
  .small-12.text-center.columns{style: "color: #990000" }
    There was a problem setting up this interactive. Please try refreshing your page.
-if @master_document_url
  - if @supplemental_documents && @supplemental_documents.size > 0
    .row
      .small-12.text-center.columns
        - most_recent = @supplemental_documents.sort_by{|d| d.updated_at }.last
        = link_to h(@buttonText), codap_link(@codap_server, most_recent, false, true), class: :"launch-button", target: "_blank"
    .row.more-space-above
      .small-12.text-center.columns
        -# This will be a link to the master document with the learners runKey
        -# when it is opened the contents of the master document will be shown
        -# When this document is saved the document-store will look for another document
        -# with the same runKey owned by the current_user and override that document
        = link_to 'Reset to Original', @master_document_url, class: :"original-reset", target: "_blank"
  - else
    .row
      .small-12.text-center.columns.end
        = link_to h(@buttonText), @master_document_url, class: :"launch-button", target: "_blank"
- else
  .row
    .small-12.text-center.columns{style: "color: #990000" }
      Error: The requested document could not be found.
:javascript
  $(document).ready(function() {
    if (#{@in_a_window.to_s}) {
      // Set all links to replace this page instead of opening yet another window.
      $('a').attr('target', '');
      return;
    }
    // Hide the launch buttons until we talk with LARA
    $('.launch-button, .original-reset').hide();
    // But show them after a while, just in case
    var showTimeoutId = setTimeout(function() {
      $('.launch-button, .original-reset').show();
    }, 10000);

    var runKey = '#{@runKey}',
        reportingUrl = '#{@report_url}',
        learnerUrl = '#{@learner_url}',
        areLoggedIn = #{!current_user.nil?},
        currentEmail = #{current_user.nil? ? "null" : "'#{current_user.email}'"},
        authFailed = #{@auth_failed.to_s};

    var phone = iframePhone.getIFrameEndpoint(),
        learnerUrlSet = false,
        state = {runKey: runKey, lara_options: { reporting_url:  reportingUrl }};

    phone.addListener('authInfo', function(info) {
      clearTimeout(showTimeoutId); // We're communicating fine, so don't automatically show the launch buttons
      if (!info["loggedIn"]) {
        // We're not supposed to be logged in.
        if (areLoggedIn) {
          // But... we are.
          if (window.location.href.indexOf('require_anonymous=') == -1) {
            // Log the current user out
            var loc = $.param.querystring(window.location.href, "require_anonymous=true");
            if (authFailed) {
              loc = $.param.querystring(loc, "window=true");
              $('.login-error .text-center').html("There was a problem setting up this interactive. <a href='" + loc + "' target='_blank'>Try again</a>");
              $('.login-error').show();
            } else {
              window.location = loc;
            }
            return;
          } else {
            $('.login-error').show();
            return;
          }
        } else {
          // And we're not logged in. Good!
          // Tell CODAP that we're running anonymously
          $('.launch-button,.original-reset').each(function() {
            var origHref = $(this).attr('href');
            $(this).attr('href', $.param.querystring(origHref, 'runAsGuest=true'));
          });
        }
      } else {
        // We're supposed to be logged in.
        if (!areLoggedIn) {
          // But... we aren't.
          if(window.location.href.indexOf('auth_provider=') == -1) {
            // Try to log a user in.
            var loc = $.param.querystring(window.location.href, { require_email: info["email"], auth_provider: info["provider"]});
            if (authFailed) {
              loc = $.param.querystring(loc, "window=true");
              $('.login-error .text-center').html("There was a problem setting up this interactive. <a href='" + loc + "' target='_blank'>Try again</a>");
              $('.login-error').show();
            } else {
              window.location = loc;
            }
            return;
          } else {
            $('.login-error').show();
            return;
          }
        } else {
          // And we are logged in. Good!
          // Are we the right person?
          if (info["email"] && info["email"] != currentEmail) {
            // Wrong person. Try to log in again.
            if(window.location.href.indexOf('require_email=') == -1) {
              // Try to log a user in.
              var loc = $.param.querystring(window.location.href, { require_email: info["email"], auth_provider: info["provider"]});
              if (authFailed) {
                loc = $.param.querystring(loc, "window=true");
                $('.login-error .text-center').html("There was a problem setting up this interactive. <a href='" + loc + "' target='_blank'>Try again</a>");
                $('.login-error').show();
              } else {
                window.location = loc;
              }
              return;
            } else {
              $('.login-error').show();
              return;
            }
          }
        }
      }

      // if we get here, we're the correct user
      phone.addListener('getInteractiveState', function () {
        phone.post('interactiveState', 'nochange');
      });
      phone.post('setLearnerUrl', learnerUrl);
      phone.post('interactiveState', state);
      $('.launch-button,.original-reset').show();
    });
    phone.addListener('getExtendedSupport', function() {
      phone.post('extendedSupport', { reset: false });
    });
    // Initialize connection after all message listeners are added!
    phone.initialize();

    // Some initial messages we're going to *always* send
    phone.post('getAuthInfo');
  });

app/views/documents/new.html.haml
%ul.breadcrumbs
  %li= link_to 'Home', root_path
  %li= link_to 'Documents', documents_path
  %li.current
    %a{href: '#'} Create

%h1 Create document

= render 'form'

app/views/documents/report.html.haml
-if @found_master_document
  - if @supplemental_documents && @supplemental_documents.size > 0
    - sorted_docs = @supplemental_documents.sort_by{|d| d.updated_at }.reverse
    .row
      .small-3.text-center.columns
        - most_recent = sorted_docs.shift  # remove the first (most recent) doc from the array and use it
        = link_to 'Launch most recent!', codap_link(@codap_server, most_recent, current_user.nil?), class: :"launch-button", target: "_blank"
      .small-9.columns
        %ul.small-block-grid-5
          - sorted_docs.each do |doc|
            %li= link_to doc.title, codap_link(@codap_server, doc, current_user.nil?), class: :"launch-button", target: "_blank"
  - else
    .row
      .small-12.text-center.columns
        No documents have been saved!
- else
  .row
    .small-12.text-center.columns{style: "color: #990000" }
      Error: The requested document could not be found.

app/views/documents/show.html.haml
- pretty_json = JSON.pretty_generate(@document.content)
- if pretty_json.size < 100000
  :javascript
    hljs.initHighlightingOnLoad();

%ul.breadcrumbs
  %li= link_to 'Home', root_path
  %li= link_to 'Documents', documents_path
  %li.current
    %a{href: '#'}= @document.title || ""

%p
  %b Title:
  = (@document.title || "") + (@document.run_key ? " [#{@document.run_key}]" : "")
%p
  %b Shared:
  = @document.shared
- if @document.owner != current_user
  %p
    %b Owner:
    = @document.owner_id
%p
  %b Content:
  %pre
    %code.json= pretty_json

- if can? :edit, @document
  = link_to 'Edit', edit_document_path(@document), class: :button