config/routes.rb
Rails.application.routes.draw do
  resources :documents

  # CODAP API
  get 'document/all' => 'documents#all'
  get 'document/open' => 'documents#open'
  get 'document/launch' => 'documents#launch', :as => :launch
  get 'document/report' => 'documents#report', :as => :report
  post 'document/save' => 'documents#save'
  post 'document/patch' => 'documents#patch'
  get 'document/rename' => 'documents#rename'
  get 'document/delete' => 'documents#delete'
  get 'user/info' => 'users#info'
  get 'user/authenticate' => 'users#authenticate'

  get 'v2/documents/:id' => 'documents_v2#open', :as => :v2_document_open
  put 'v2/documents/:id' => 'documents_v2#save', :as => :v2_document_save
  patch 'v2/documents/:id' => 'documents_v2#patch', :as => :v2_document_patch
  post 'v2/documents' => 'documents_v2#create', :as => :v2_document_create
  get 'v2/documents/:id/launch' => 'documents_v2#launch', :as => :v2_document_launch
  get 'v2/documents/:id/autolaunch' => 'documents_v2#autolaunch', :as => :v2_document_autolaunch
  post 'v2/documents/create_keys' => 'documents_v2#create_keys', :as => :v2_document_create_keys

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks"}
  resources :users

  #examples
  get "/examples/:example" => "examples#show"
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:"data-alert" => true, :class => "alert-box radius #{name.to_s == "notice" ? "success" : "alert"}"}
      = msg
      %a{:href => "#", :class => "close"}= "&times;".html_safe

app/views/layouts/_navigation.html.haml
.sticky
  %nav.top-bar{data: {topbar: true}}
    %ul.title-area
      %li.name
        %h1= link_to 'Home', root_path

    %section.top-bar-section
      %ul.left
        = render 'layouts/navigation_links'
      %ul.right
        - if user_signed_in?
          %li.has-dropdown
            %a.name{href: '#'}= current_user.name
            %ul.dropdown
              %li.name
                %h1
                  %small
                    %a.text-right{href: '#', data: {reveal_id: 'switchUserModal'} }= "Not #{current_user.name}?"
          - if User.devise_modules.include?(:registerable)
            %li= link_to 'Edit account', edit_user_registration_path
          %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
        - else
          %li= link_to 'Sign in', new_user_session_path
          - if User.devise_modules.include?(:registerable)
            %li= link_to 'Sign up', new_user_registration_path

    - if user_signed_in?
      #switchUserModal.reveal-modal{data: {reveal: true} }
        %p.lead Not the right user?
        %p There are some things you can do to ensure you're logged in as the correct user:
        %p
          %ul
            %li
              First, try
              = link_to 'signing out', destroy_user_session_path, :method=>'delete'
              and signing back in.
        %p If you've already signed out and signed back in and the account is still not correct:
        - current_authentication = current_user.authentications.order(updated_at: :desc).first
        - if current_authentication && current_authentication.provider.start_with?('cc_portal_')
          - portal_url = Concord::AuthPortal.url_for_portal(current_authentication.provider.sub('cc_portal_', ''))
          %p
            %ul
              %li
                Try
                = link_to 'signing out of the portal', portal_url, target: '_blank'
                through which you last logged in,
              %li
                Then, come back here and
                = link_to 'sign out', destroy_user_session_path, :method=>'delete'
                and sign back in.


        %a.close-reveal-modal &#215;

app/views/layouts/_navigation_links.html.haml
-# add navigation links to this file
- if can? :list, Document
  %li= link_to 'Documents', documents_path
- if can? :list, User
  %li= link_to 'Users', users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'DocumentStore'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Documentstore'}"}
    = stylesheet_link_tag '//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.2/styles/tomorrow.min.css', media: 'all'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.2/highlight.min.js'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .row
      .large-12.columns
        = render 'layouts/messages'

    .row
      .large-12.columns
        = yield

app/views/layouts/example.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'DocumentStore'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Documentstore'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{style: 'margin:0px; padding:0px'}
    = yield

app/views/layouts/launch.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'DocumentStore'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Documentstore'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{style: 'background-color: #b6e2eb;'}
    .row.more-space-above
      .large-12.columns
        = yield